New filters
jeancochrane/philly-fliers pull request #4
Opened 2018-07-31 16:02 UTC by jeancochrane

# Overview

Adds new filters for datetime ranges and polygon boundaries.

## Demo

Filtering by date:

![date-filter](https://user-images.githubusercontent.com/14170650/43471341-c0e3ee6c-94b8-11e8-87aa-23628d8a8349.png)

Filtering by polygon:

![filter-polygon](https://user-images.githubusercontent.com/14170650/43471354-ca62e2cc-94b8-11e8-81e0-67edb37884d4.png)

## Testing instructions

The frontend doesn't have tests yet. To test the new filters, you'll have to run the server and play around with them:

```bash
# Build containers and install NPM modules.
./scripts/update

# Run the dev server.
./scripts/server
```

Travis will run unit tests for the schema editor and Grout server to confirm that there are no regressions in those apps. If you'd like to run those tests yourself, you can use the `test` script:

```bash
./scripts/test
```

2018-08-01 20:00 UTC, flibbertigibbet requested changes
The new filters work well, and the code here looks good.

Not sure if it's a result of this PR, but I did notice the 'search' button for the other filters isn't working for me in Chrome or Firefox on Ubuntu. There's a console error:
`Invalid prop: type check failed for prop "filters". Expected Array, got Object.`

2018-08-01 20:11 UTC, jeancochrane commented
Good catch @flibbertigibbet! Looks like I forgot that `Array.prototype.concat` doesn't mutate arrays in place. Should be fixed now.

That console error seems to be unrelated to the filter issue, and is possibly a bug in the linter. In any case, it shouldn't affect the filter functionality.

Let me know if anything else seems broken!

2018-08-01 22:56 UTC, flibbertigibbet approved these changes
The new filters are working well, so I think this is good to go in!

Looks like there may be some more work to do around the existing text filters, though, so I'd suggest making an issue for that, and maybe also the console error.

On entering any text in the search, I get no results, even if the text is an exact match. Clearing the filter still returns the one sample record.

2018-08-02 13:31 UTC, jeancochrane commented
I'll take a look at the filters! It's likely a simple logic bug introduced by this PR, since I had to rebase off of the app components/CI branch to get this PR up to date.

Given that this is the second or third time that filter functionality has broken after refactoring, I think that once we pull this PR in it'll be about time for some unit tests. Thanks for your patient QA in the meantime!

2018-08-02 14:45 UTC, jeancochrane commented
In https://github.com/azavea/grout/pull/10 I added a new test to Grout that confirms the problem with the filters is in Grout core, not this PR. (See the [failing Travis build](https://travis-ci.org/azavea/grout/builds/411317156) for a traceback.) Great catch, @flibbertigibbet!

Opened up https://github.com/azavea/grout-2018-fellowship/issues/47 to track the filtering bug. For now, I'm going to pull in this PR since the bug is unrelated to the app.

2018-08-02 14:45 UTC, merged